services : 
    api :  
        image : url-shortener
        build :
              dockerfile: Dockerfile
              context : .
        depends_on : 
              - postgres
        environment :
                DB_HOST : ${DB_HOST}
                DB_USER : ${DB_USER}
                DB_PASSWORD : ${DB_PASSWORD}
                DB_NAME : ${DB_NAME}
              
                DATABASE_URL : url-shortener://DB_USER:DB_PASSWORD@postgres:5432/DB_NAME
                NODE_ENV : development
                PORT : ${PORT}
        ports : 
            - "3000:3000"
    
    postgres: 
        image : postgres:latest
        ports : 
            - "5432:5432"
        environment : 
            POSTGRES_USER : DB_USER
            POSTGRES_PASSWORD : DB_PASSWORD
            POSTGRES_DB : DB_NAME
            PORT : ${DB_PORT}

    
        