services:
  api:
    build: .
    depends_on:
      - postgres

    env_file:
      - .env

    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}
    ports:
      - '3002:3000'
      - '6380:6379'

    networks:
      - url_network

  postgres:
    image: postgres:latest

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - '5432:5432'

    volumes:
      - url_volume:/var/lib/postgresql/data

    networks:
      - url_network

volumes:
  url_volume:

networks:
  url_network:
